server:
  port: 8001
spring:
  application:
    name: feng-shortlink-project
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  data:
    redis:
      host: 192.168.187.101
      port: 6379
      password: 51213002
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.187.101:8848
short-link:
  stats:
    locale:
      amap-key: d8ff1fbaa0db78890a8659a25ace740f
  domain: "baidu.com:8001"
  goto-domain:
    white-list:
      enable: true
      names: '哔哩哔哩, 知乎, 掘金, 博客园, 抖音, 淘宝......'
      details:
        - nageoffer.com
        - bilibili.com
        - zhihu.com
        - juejin.cn
        - cnblogs.com
        - douyin.com
        - baidu.com
        - 0daydown.com
        - 126.com
        - 126.net
        - 163.com
        - 178.com
        - 199it.com
        - 36kr.com
        - 39.net
        - 56.com
        - 58.com
        - 58pic.com
        - 699pic.com
        - aldwx.com
        - alibaba.com
        - alimama.com
        - alipay.com
        - alipayobjects.com
        - aliued.com
        - aliyun.com
        - amap.com
        - ancda.com
        - ant.design
        - antfin-inc.com
        - antfin.com
        - appinn.com
        - appinn.net
        - apple.com
        - babybus.com
        - baidu.com
        - baiduwp.com
        - baomihua.com
        - bbtree.com
        - beisen.com
        - bible.com
        - bilibili.*
        - bilivideo.com
        - bing.com
        - bitbucket.org
        - bluedoc.io
        - bootcss.com
        - btsync.org
        - cctv.com
        - cdnjs.com
        - chainnews.com
        - chinaz.com
        - chongdiantou.com
        - cli.im
        - cmbchina.com
        - cnbeta.com
        - cnzz.com
        - coloros.com
        - cowtransfer.com
        - csdn.net
        - ctrip.com
        - damengxiang.me
        - dangdang.com
        - ddrk.me
        - didiglobal.com
        - digitalocean.com
        - dingtalk.com
        - dingtalkapps.com
        - dji.com
        - docer.com
        - docschina.org
        - douban.*
        - doubanio.com
        - douyin.com
        - douyutv.com
        - doyoudo.com
        - draw.io
        - duoshao.app
        - ele.me
        - etao.com
        - ewei.com
        - feng.com
        - figmachina.com
        - figmacn.com
        - fir.im
        - fliggy.com
        - foundertype.com
        - fydeos.com
        - googletagmanager.com
        - gratisography.com
        - growingio.com
        - guokr.com
        - hao123.com
        - haosou.com
        - hdb.com
        - houxu.app
        - huaban.com
        - iciba.com
        - icloud.com
        - ifanr.com
        - ifeng.com
        - iguoguo.net
        - iina.io
        - infoq.com
        - intercomcdn.com
        - ipip.net
        - iqiyi.com
        - ithome.com
        - itjuzi.com
        - jd.com
        - jianshu.*
        - jianshuapi.com
        - jikipedia.com
        - kf5.com
        - ksyungslb.com
        - kuaidi100.com
        - kuaishou.com
        - kugou.com
        - lanhuapp.com
        - lanzous.com
        - le.com
        - leancloud.app
        - liantu.com
        - linkedin.com
        - linode.com
        - lizhi.fm
        - lkkdesign.com
        - lvmama.com
        - ly.com
        - macrr.com
        - magi.com
        - meituan.com
        - meizu.com
        - mgtv.com
        - mi.com
        - miaopai.com
        - microbit.org
        - minapp.com
        - miwifi.com
        - mu6.me
        - netease.com
        - nipic.com
        - nobook.com
        - now.sh
        - oneplus.com
        - oppo.com
        - oschina.net
        - oursketch.com
        - outlook.com
        - panda.tv
        - panduoduo.net
        - pc6.com
        - pexels.com
        - pgyer.com
        - piaoquantv.com
        - pingwest.com
        - pluwen.com
        - polyfill.io
        - pptv.com
        - processon.com
        - qichacha.com
        - qiuziti.com
        - qq.com
        - qyer.com
        - sc115.com
        - shimo.im
        - sina.com
        - slack.com
        - smartisan.com
        - smzdm.com
        - sogou.com
        - sohu.com
        - soku.com
        - soso.com
        - speedtest.net
        - sspai.com
        - suning.com
        - surface.wiki
        - taihe.com
        - talkingdata.com
        - taobao.com
        - taobaocdn.com
        - tencent.com
        - thetype.com
        - tianyancha.com
        - tinyservices.net
        - tmall.com
        - toutiao.com
        - trontv.com
        - tuchong.com
        - tudou.com
        - tuniu.com
        - typeisbeautiful.com
        - ucweb.com
        - uedna.com
        - uigreat.com
        - uisdc.com
        - umeng.com
        - undraw.co
        - visualhunt.com
        - vmall.com
        - vultr.com
        - wallhaven.cc
        - wandoujia.com
        - weather.com
        - webfont.com
        - weibo.com
        - woshipm.com
        - xdccpro.com
        - xiami.com
        - xiaomi.com
        - xiaotu.io
        - xueqiu.com
        - xunlei.com
        - xywy.com
        - yinxiang.com
        - yinyuetai.com
        - youdao.com
        - youku.com
        - yuque.com
        - zanmeishi.com
        - zhangxinxu.com
        - zhaopin.com
        - zhihu.com
        - zhimg.com
        - zhongguose.com
rocketmq:
  name-server: 192.168.187.101:9876  # RocketMQ NameServer 地址
  producer:
    group: shortlink-stats-producer-group  # 生产者组
  consumer:
    group: shortlink-stats-consumer-group  # 消费者组
